spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:todo
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: create
#        show-sql: true
        dialect: org.hibernate.dialect.H2Dialect
#