spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: ${DRIVER_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#        show-sql: true