spring:
  datasource:
    url: jdbc:mariadb://43.203.245.150:3306/todo?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
